name: mle_interview
channels:
  - conda-forge
  - defaults
dependencies:
  - ipykernel=6.2.0
  - matplotlib-base=3.4.3
  - matplotlib-inline=0.1.2
  - numpy=1.21.2
  - pandas=1.3.2
  - scikit-learn=0.24.2
  - scipy=1.7.1
  - seaborn=0.11.2
  - seaborn-base=0.11.2
  - tensorflow=2.4.1